# coding: utf-8

"""
    Dohyo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ra_rem.models.fuel_data import FuelData

class TestFuelData(unittest.TestCase):
    """FuelData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FuelData:
        """Test FuelData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FuelData`
        """
        model = FuelData()
        if include_optional:
            return FuelData(
                fuel_type = '',
                value = 1.337,
                units = ''
            )
        else:
            return FuelData(
                fuel_type = '',
                units = '',
        )
        """

    def testFuelData(self):
        """Test FuelData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
