# coding: utf-8

"""
    Dohyo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ra_rem.models.metrics import Metrics

class TestMetrics(unittest.TestCase):
    """Metrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Metrics:
        """Test Metrics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Metrics`
        """
        model = Metrics()
        if include_optional:
            return Metrics(
                mean = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
                median = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
                percentile_20 = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
                percentile_80 = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ]
            )
        else:
            return Metrics(
                mean = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
                median = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
                percentile_20 = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
                percentile_80 = [
                    ra_rem.models.fuel_data.FuelData(
                        fuel_type = '', 
                        value = 1.337, 
                        units = '', )
                    ],
        )
        """

    def testMetrics(self):
        """Test Metrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
