# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.

    The version of the OpenAPI document: 1.3.2
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.api.building_profiler_api import BuildingProfilerApi


class TestBuildingProfilerApi(unittest.TestCase):
    """BuildingProfilerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BuildingProfilerApi()

    def tearDown(self) -> None:
        pass

    def test_get_home_profile_by_address(self) -> None:
        """Test case for get_home_profile_by_address

        Get home profile by address
        """
        pass

    def test_get_home_profile_by_address_components(self) -> None:
        """Test case for get_home_profile_by_address_components

        Get home profile by address components
        """
        pass


if __name__ == '__main__':
    unittest.main()
