# coding: utf-8

"""
    Dohyo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ra_rem.models.valid_upgrade import ValidUpgrade

class TestValidUpgrade(unittest.TestCase):
    """ValidUpgrade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidUpgrade(self):
        """Test ValidUpgrade"""
        # inst = ValidUpgrade()

if __name__ == '__main__':
    unittest.main()
