# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.

    The version of the OpenAPI document: 1.3.2
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.models.water_heater_fuel import WaterHeaterFuel

class TestWaterHeaterFuel(unittest.TestCase):
    """WaterHeaterFuel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaterHeaterFuel(self):
        """Test WaterHeaterFuel"""
        # inst = WaterHeaterFuel()

if __name__ == '__main__':
    unittest.main()
