# coding: utf-8

"""
    Residential Electrification Model API

    An API for REM, the Residential Electrification Model.

    The version of the OpenAPI document: 1.3.2
    Contact: datascience@rewiringamerica.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rewiringamerica_rem.models.sampling_details import SamplingDetails

class TestSamplingDetails(unittest.TestCase):
    """SamplingDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SamplingDetails:
        """Test SamplingDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SamplingDetails`
        """
        model = SamplingDetails()
        if include_optional:
            return SamplingDetails(
                num_samples = 380,
                num_excluded_samples = 20
            )
        else:
            return SamplingDetails(
                num_samples = 380,
                num_excluded_samples = 20,
        )
        """

    def testSamplingDetails(self):
        """Test SamplingDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
