# coding: utf-8

"""
    Dohyo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ra_rem.models.impact import Impact

class TestImpact(unittest.TestCase):
    """Impact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Impact:
        """Test Impact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Impact`
        """
        model = Impact()
        if include_optional:
            return Impact(
                energy = ra_rem.models.metrics.Metrics(
                    mean = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    median = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    percentile_20 = [
                        
                        ], 
                    percentile_80 = [
                        
                        ], ),
                emissions = ra_rem.models.metrics.Metrics(
                    mean = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    median = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    percentile_20 = [
                        
                        ], 
                    percentile_80 = [
                        
                        ], ),
                cost = ra_rem.models.metrics.Metrics(
                    mean = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    median = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    percentile_20 = [
                        
                        ], 
                    percentile_80 = [
                        
                        ], )
            )
        else:
            return Impact(
                energy = ra_rem.models.metrics.Metrics(
                    mean = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    median = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    percentile_20 = [
                        
                        ], 
                    percentile_80 = [
                        
                        ], ),
                emissions = ra_rem.models.metrics.Metrics(
                    mean = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    median = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    percentile_20 = [
                        
                        ], 
                    percentile_80 = [
                        
                        ], ),
                cost = ra_rem.models.metrics.Metrics(
                    mean = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    median = [
                        ra_rem.models.fuel_data.FuelData(
                            fuel_type = '', 
                            value = 1.337, 
                            units = '', )
                        ], 
                    percentile_20 = [
                        
                        ], 
                    percentile_80 = [
                        
                        ], ),
        )
        """

    def testImpact(self):
        """Test Impact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
