# coding: utf-8

"""
    Dohyo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ra_rem.api.building_profiler_api import BuildingProfilerApi


class TestBuildingProfilerApi(unittest.TestCase):
    """BuildingProfilerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BuildingProfilerApi()

    def tearDown(self) -> None:
        pass

    def test_building_profiler_get_home_profile(self) -> None:
        """Test case for building_profiler_get_home_profile

        Get Home Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
