# coding: utf-8

"""
    Dohyo

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class FuelDataRates(BaseModel):
    """
    A class to represent fuel data for rates.  Attributes ----------     fuel_type (str): The type of fuel. Values can be \"electricity\", \"natural_gas\", \"propane\", \"fuel_oil\", or \"net\".     rate_type (str): The type of rate. Values can be \"fixed\" or \"volumetric\".     value (float): The numerical value of what the metric is.     units (str): The measurement.
    """ # noqa: E501
    fuel_type: StrictStr
    value: Optional[Union[StrictFloat, StrictInt]] = 0.0
    units: StrictStr
    rate_type: Optional[StrictStr] = 'volumetric'
    __properties: ClassVar[List[str]] = ["fuel_type", "value", "units", "rate_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FuelDataRates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FuelDataRates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fuel_type": obj.get("fuel_type"),
            "value": obj.get("value") if obj.get("value") is not None else 0.0,
            "units": obj.get("units"),
            "rate_type": obj.get("rate_type") if obj.get("rate_type") is not None else 'volumetric'
        })
        return _obj


