# Publish Python stubs to PyPi.

name: Publish stubs

# Prod deployments will automatically generate code into the repo
on:
  push

permissions:
  id-token: write

jobs:
  #----------------------------------------------
  #               Publish stubs
  #----------------------------------------------
  publish-stubs:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.12

        - name: Install Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python3 -
            poetry --version  # Verify the installed Poetry version
            poetry install

        - name: Install twine
          run: pip install twine

        - name: Build the package
          run: |
            poetry build --verbose --no-interaction
            ls -l dist

        - name: Publish the package
          run: poetry run twine upload --repository testpypi dist/*
